### ISSUE TITLE
Some commands are not working

### ISSUE THREAD

**Issue by despawningbone** [Shortninja66/StaffPlus#16]
I haven't tested everything, but i got 2 errors for /staff and /cps respectively:

```
 [20:55:09] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'staff' in net.shortninja.staffplus.command.cmd.mode.ModeCmd(staff)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
    at net.shortninja.staffplus.command.cmd.mode.ModeCmd.toggleMode(ModeCmd.java:68) ~[?:?]
    at net.shortninja.staffplus.command.cmd.mode.ModeCmd.execute(ModeCmd.java:60) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    ... 14 more
```

This was caused by me doing /staff. i got the right permission.

The other one is for /cps despawningbone(myself)(i didn't have people to test it currently):

```
[21:14:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'cps despawningbone' in net.shortninja.staffplus.command.cmd.mode.CpsCmd(cps)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.IllegalAccessError: tried to access class net.shortninja.staffplus.player.attribute.mode.handler.CpsHandler$1 from class net.shortninja.staffplus.player.attribute.mode.handler.CpsHandler
    at net.shortninja.staffplus.player.attribute.mode.handler.CpsHandler.startTest(CpsHandler.java:40) ~[?:?]
    at net.shortninja.staffplus.player.attribute.mode.handler.GadgetHandler.onCps(GadgetHandler.java:205) ~[?:?]
    at net.shortninja.staffplus.command.cmd.mode.CpsCmd.execute(CpsCmd.java:51) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    ... 14 more
```

When i do that it will say "Running CPS test on despawningbone for 10 seconds..." but then right after it it will show the error in the console and "an internal error occured..." on my chat.

There is this warn when i start the plugin too: [21:17:16] [Server thread/WARN]: [StaffPlus] Default system encoding may have misread config.yml from plugin jar

Also, one side note is that i found out when i do /notes to give notes to a player it wont show up on /examine 's player notes. Is it a bug?

Am i doing the config wrong?  there was a error that made the plugin not useable because my server doesn't support unicode (», •) for some reason, so i removed them and the plugin worked (lang_en.yml).
## Please help!

Server running git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Plugins (41): CoreProtect, TTA, BlockParticles, WorldEdit, CrazyCrates, AnimatedScoreboard, CustomPermissionMessages, Essentials, iChatPlus, PlaceholderAPI, DisableJoinMessage, PlugMan, HolographicDisplays, VoidSpawn, WorldGuard, Friends2_0, AutoRestart, EssentialsProtect, EssentialsChat, Duels, EssentialsAntiBuild, PermissionsEx, NoEscape, hub, mcMMO, Vault, EssentialsSpawn, MyCommand, OreGeneratorRevolution, WithdrawAdvanced, SignShop, SilkSpawners, ChatFormat, ASkyBlock, CrazyAuctions, BossShop, EpicRename, StaffPlus, SlowChat, ChatColorTags, Chatmanager

StaffPlus is running version 3.0.8

**Comment by despawningbone** [comment]
I also got this error too when i do "/report despawningbone test" (again, despawningbone is myself):

```
[21:38:53] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'report despawningbone test' in net.shortninja.staffplus.command.cmd.infraction.ReportCmd(report)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
    at net.shortninja.staffplus.command.cmd.infraction.ReportCmd.sendReport(ReportCmd.java:144) ~[?:?]
    at net.shortninja.staffplus.command.cmd.infraction.ReportCmd.execute(ReportCmd.java:70) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
    ... 14 more

```

**Comment by Shortninja66** [comment]
revive says "NO FOUND" when there is no inventory to restore. you must die in order to get a revive.

i'll look into the other stacktrace when i get the chance.

**Comment by despawningbone** [comment]
I died before I executed that command though...

**Comment by Shortninja66** [comment]
was your inventory empty? revives are also not saved through restarts and are not able to be restored twice.,

**Comment by despawningbone** [comment]
It is executed right after i died(tested both normally (lava damage etc) and /kill) and my inventory have items in it.

**Comment by despawningbone** [comment]
ok so revive is only working with others not on yourself i just tested.

**Comment by Shortninja66** [comment]
i just tested this out and i don't see what your issue is. if you could give me more information on how you triggered the error, then i can do more.

be sure to upgrade to the latest version of staff+ as well.
