### ISSUE TITLE
Staff+ not 1.11 ready =   :(

### ISSUE THREAD

**Issue by Jawakotb** [Shortninja66/StaffPlus#20]
Hello!   I and my server staff are simply in love with this plugin (3.2.1)and we are hoping we could use this on our new 1.11 server..... but alas the plugin automatically disables itself on 1.11.  Was hoping that this new version of MC could be supported..... will it?

Thank you for the awesome plugin and for looking into this error/version update request.

-------------------------
Running Spigot 1.11(latest)
Oracle Java 1.8.0_111-b14
Ubuntu 16.04LTS
32GB Mem - 500GB SSD
Intel Xeon
-------------------------

Error in Console:

[Staff+] This version of Minecraft is not supported!  If you have just updated to a brand new server version, check the Spigot plugin page.
[StaffPlus] Disabling StaffPlus v3.2.1
[Staff+] Staff+ is now Disabled!
[ERROR]: Error occurred while disabling StaffPlus v3.2.1 (Is it up to date?)
java.lang.NullPointerException
	at net.shortninja.staffplus.StaffPlus.saveUsers(StaffPlus.java:121) ~[?:?]
	at net.shortninja.staffplus.StaffPlus.stop(StaffPlus.java:247) ~[?:?]
	at net.shortninja.staffplus.StaffPlus.onDisable(StaffPlus.java:110) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at net.shortninja.staffplus.StaffPlus.start(StaffPlus.java:134) [Staff+.jar:?]
	at net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:103) [Staff+.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-f950f8e-1c07d5c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot.jar:git-Spigot-f950f8e-1c07d5c]

**Comment by Lauris1988** [comment]
Totally the same thing for me! I am looking forward to 1.11 version

**Comment by Shortninja66** [comment]
1.11 support should be released today. sorry for the postponed update, i was in the hospital.
