### ISSUE TITLE
AsyncPlayerChatEvent - Staff+ Error

### ISSUE THREAD

**Issue by Neeonn** [Shortninja66/StaffPlus#32]
Hi. I've been using Staff+ for a long time now and I've recently found this error in console:

`
[19:33:01] [Async Chat Thread - #76/ERROR]: Could not pass event AsyncPlayerChatEvent to StaffPlus v3.2.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.chat(PlayerConnection.java:1036) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:975) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:47) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.ArrayIndexOutOfBoundsException`

I don't like having any errors/warnings in my console because I'm trying to make server as lightweight as possible but this plugin is not letting me do my thing. Hope that you'll help me fix this!

**Comment by rianexists** [comment]
Hi @Neeonn,

If you read [this](https://www.spigotmc.org/threads/a-reflection.219197/), you'll find that Gavin is no longer working on this plugin. If someone chooses to continue this, please feel free to get help from them.

For now, just disable it and find a replacement or live with the errors.

Thanks,
Rian

**Comment by jcxldn** [comment]
@Neeonn it looks like it is caused by PluginManager, do you have the latest Staff+ and PluginManager version?

**Comment by Neeonn** [comment]
I'm sorry to hear what happened to him..

@Prouser123 I'm actually running latest version of Staff+ but I'm not using any kind of PluginManager plugin.. I guess this was because I installed PlugMan and because of that it got me this error but now it's all fine. Thanks for replying.

Again, I'm sorry to hear what happened to him. Didn't really know him, I'm new to the whole spigot/bukkit community and it's sad to hear that.. :/

**Comment by RianOBrian** [comment]
Hey, @Neeonn.

In your OP, you said you'd been using the plugin for ages. If so, how are you able to still be new to the community?

Just wondering, that's all.

**Comment by Neeonn** [comment]
I have said that I've been using it for a "long time" which means that I didn't specify how long I've been using it for.
I sometime visit spigot and bukkit dev just to see new plugins and new things, I don't communicate to other members or reply to the comments. That's why I said that I'm new to "community".
