### ISSUE TITLE
NPE Spamming console

### ISSUE THREAD

**Issue by Strvm** [Shortninja66/StaffPlus#66]
There:

`31.08 21:40:45 [Server] Server thread/ERROR Could not pass event InventoryCloseEvent to StaffPlus v3.2.2
31.08 21:40:45 [Server] INFO org.bukkit.event.EventException
31.08 21:40:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:852) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.closeInventory(EntityPlayer.java:787) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:440) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [?:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
31.08 21:40:45 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot1.8.8.jar:git-Spigot-db6de12-07c3001]
31.08 21:40:45 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
31.08 21:40:45 [Server] INFO Caused by: java.lang.NullPointerException`

**Comment by Legoman99573** [comment]
#34 not going to ever get a response unless you find a fork of this project
