### ISSUE TITLE
Console getting spammed with message

### ISSUE THREAD

**Issue by dudefoxlive** [Shortninja66/StaffPlus#73]
I want to use this plugin for ore alerts but console keeps getting spammed with this. Its quite annoying as when I'm not on the server I use console to see who is online and what is happening. We are running Paper MC 1.15.2.

[15:21:06] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to StaffPlus v3.3.2.4
java.lang.NullPointerException: null
        at net.shortninja.staffplus.server.listener.entity.EntityDamageByEntity.onDamage(EntityDamageByEntity.java:48) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor84.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-353]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-353]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-353]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-353]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:240) ~[patched_1.15.2.jar:git-Paper-353]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:874) ~[patched_1.15.2.jar:git-Paper-353]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:851) ~[patched_1.15.2.jar:git-Paper-353]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1040) ~[patched_1.15.2.jar:git-Paper-
353]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1691) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity0(EntityHuman.java:878) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1049) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:801) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:775) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.Explosion.a(Explosion.java:188) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.World.createExplosion(World.java:1025) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.WorldServer.createExplosion(WorldServer.java:1647) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.World.createExplosion(World.java:1015) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.EntityCreeper.explode(EntityCreeper.java:217) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.EntityCreeper.tick(EntityCreeper.java:122) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:807) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.World.a(World.java:879) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:532) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-353]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-353]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

Plugins:
AdvancedLogger
ClearLagg
CoreProtect
DummyFawe
EssentialsX
EssentialsXChat
FastAsyncWorldEdit
GriefPrevention
Harbor
Holograms
IPLogger
InventoryRollback
LibsDisguises
Litebans
LoginSecurity
LuckPerms
NoteblockAPI
OpenINV
PacketListenerAPI
PlaceholderAPI
Plugman
ProtocolLib
ProtocolSupport
SonicScrewDriver
Staff+
SuperVanish
TAB
Vault
ViaVersion
WebConsole
AntiVPN
FastLogin
JukeBox
Spark
WorldGuard

**Comment by FireRoz** [comment]
I have the same issue.
and the support team here is not the brightest.
Try resetting your config though. worked for me

**Comment by RexyTheDev** [comment]
> I have the same issue.
> and the support team here is not the brightest.
> Try resetting your config though. worked for me

most likely because the "Support Team" passed away 3 years ago. ShortNinja is no longer with us.
