### ISSUE TITLE
console errors after modifying the config

### ISSUE THREAD

**Issue by FireRoz** [Shortninja66/StaffPlus#79]
hi,
I downloaded "Staff+" and enjoyed it for a while.
I went and edited the config:
https://pastebin.com/AjK0Cpm6

And then I got these errors:
`01:32 PM [INFO] [Staff+] Version protocol set to 'v1_8_R3'.
01:32 PM [WARN] Exception in thread "pool-55-thread-1" 
01:32 PM [WARN] java.lang.RuntimeException: java.lang.IllegalArgumentException: Duplicate handler name: packet_listener_player
01:32 PM [WARN]         at org.inventivetalent.packetlistener.channel.INCChannel$1.run(INCChannel.java:61)
01:32 PM [WARN]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
01:32 PM [WARN]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
01:32 PM [WARN]         at java.lang.Thread.run(Thread.java:748)
01:32 PM [WARN] Caused by: java.lang.IllegalArgumentException: Duplicate handler name: packet_listener_player
01:32 PM [WARN]         at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
01:32 PM [WARN]         at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:158)
01:32 PM [WARN]         at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
01:32 PM [WARN]         at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66)
01:32 PM [WARN]         at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:283)
01:32 PM [WARN]         at org.inventivetalent.packetlistener.channel.INCChannel$1.run(INCChannel.java:59)
01:32 PM [WARN]         ... 3 more
01:32 PM [WARN] Exception in thread "pool-55-thread-2" 
01:32 PM [WARN] java.lang.RuntimeException: java.lang.IllegalArgumentException: Duplicate handler name: packet_listener_player
01:32 PM [WARN]         at org.inventivetalent.packetlistener.channel.INCChannel$1.run(INCChannel.java:61)
01:32 PM [WARN]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
01:32 PM [WARN]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
01:32 PM [WARN]         at java.lang.Thread.run(Thread.java:748)
01:32 PM [WARN] Caused by: java.lang.IllegalArgumentException: Duplicate handler name: packet_listener_player
01:32 PM [WARN]         at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
01:32 PM [WARN]         at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:158)
01:32 PM [WARN]         at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
01:32 PM [WARN]         at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66)
01:32 PM [WARN]         at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:283)
01:32 PM [WARN]         at org.inventivetalent.packetlistener.channel.INCChannel$1.run(INCChannel.java:59)
01:32 PM [WARN]         ... 3 more
01:32 PM [ERROR] Error occurred while enabling StaffPlus v3.2.2 (Is it up to date?)
01:32 PM [INFO] FireRoz issued server command: /staff`
I have downloaded the latest version, and I have no idea what this error means. I searched for it (control f) and found no results.
Please help!

**Comment by RexyTheDev** [comment]
Just an FYI, the creator of this plugin passed away 3 years ago, Please go to https://github.com/Qballl/StaffPlus if you want support.
